apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-staging
  namespace: flux-system
spec:
  interval: 5m

  path: ./stacks/staging
  prune: true

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  wait: true
  timeout: 5m
  serviceAccountName: flux-deployer
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - target:
        kind: Gateway
        name: eastwest-gateway
      patch: |-
        apiVersion: gateway.networking.k8s.io/v1
        kind: Gateway
        metadata:
          name: eastwest-gateway
          labels:
            topology.istio.io/network: network-homelab
          annotations:
            io.cilium/lb-ipam-ips: 192.168.10.254
    - target:
        kind: Gateway
        name: http-gateway
      patch: |-
        apiVersion: gateway.networking.k8s.io/v1
        kind: Gateway
        metadata:
          name: http-gateway
          annotations:
            io.cilium/lb-ipam-ips: 192.168.10.240
    - target:
        kind: Gateway
        name: iam-gateway
      patch: |-
        apiVersion: gateway.networking.k8s.io/v1
        kind: Gateway
        metadata:
          name: iam-gateway
          annotations:
            io.cilium/lb-ipam-ips: 192.168.10.241
