apiVersion: v1
kind: Secret
metadata:
    name: dbgate-secret
stringData:
    username: ENC[AES256_GCM,data:2D1PtSY=,iv:SSbl2Awmmx5lznrJqTFLAOinjxBiF6LQraEf/jDfsQM=,tag:UWV6likIRbUI5rl+jEaKIQ==,type:str]
    password: ENC[AES256_GCM,data:+ZYEtDVPquZWpFIaKjxEg7c8L1I=,iv:qKSA2SLJKAumqgEPw0fcjxYhQ2rAdIJOWwT2f2gKMI8=,tag:NHbN4QEGEtKVH7jXTb1PPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVE1NcXhHczJGbytITVdT
            eVkxS0grcG9HbWpIWG40cjAwK2lsWlVPL1JzClRadmZXV1RnQVpSaVBydUlZOTRw
            Wm5hT3RlbGs5ZmREeUhLQ3hyandoMHMKLS0tIHZMbkU3K2RoY2MzVVlMck5vZXhI
            TkVGWVI0WDkvazBqeXFqR2tzcHFJWFEKuZhr1G/wGNLqsJ5yvqYGSK+YqXnkuqZY
            ZYQOhFJApV/ARdwHPKqQKzufi8Vnu+0Y3lwAlQehcSAapoxFXTIU4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5f087xu2603udrt02z7mxzfrw7tnd6xer3h6dfqc3eruava7qmqauygh7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T16:20:36Z"
    mac: ENC[AES256_GCM,data:31m99WDzQWIzjzAVTEWKneNgWwDSk45C/dI4NNyOOpzRKghqwOo43mrUsj802sbiCk5pvjtVw3zl8bZFIeLWJthSvCdjN87kkUpQP1pYhS7pMdmX/BVzbLOHBoBbaua+P/GIrhEf+9RnbpX/3fmsggtrIgoZD8rAt0yKdHeBEiY=,iv:UEFrXaFpY6/82tGGmj7Xe2of8tR6TmoZbCdYJoA2998=,tag:QpSLkue+gG+9zeT9IOG9Wg==,type:str]
    version: 3.13.1
