---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2announcement
spec:
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""
  interfaces:
    - enp0s31f6
  externalIPs: true
  loadBalancerIPs: true
