apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure/cilium
  - ../../../infrastructure/namespaces.yaml
  - ../../../infrastructure/istio
  - ../../../infrastructure/gateway-api
  - ../../../infrastructure/longhorn
  - ../../../infrastructure/cert-manager
  - ../../../infrastructure/openebs
  - ../../../infrastructure/garage
  - ../../../infrastructure/cloudnative-pg
  - ../../../infrastructure/dbgate
  - ../../../infrastructure/monitoring-backends
  - ../../../infrastructure/monitoring-collector
  - homelab-cacerts.yaml
patches:
  - target:
      kind: HelmRelease
      name: istio-istiod
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: istio-istiod
      spec:
        values:
          global:
            meshID: duynch-mesh
            multiCluster:
              clusterName: homelab
            network: network-homelab
  - target:
      kind: HelmRelease
      name: istio-ztunnel
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: istio-istiod
      spec:
        values:
          multiCluster:
            clusterName: homelab
          global:
            network: network-homelab
  - target:
      kind: Namespace
      name: istio-system
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: istio-system
        labels:
          topology.istio.io/network: network-homelab
  - target:
      kind: Namespace
      name: observability-stack
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: observability-stack
        labels:
          topology.istio.io/network: network-homelab
