---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: observability-stack
spec:
  interval: 10m
  chart:
    spec:
      chart: victoria-metrics-single
      version: ">= 0.13.0"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    server:
      # Low resource optimizations for homelab
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      retentionPeriod: "1" # 1 month
      persistentVolume:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 15Gi
        storageClass: longhorn
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              name: victoria-metrics-victoria-metrics-single-server
            patch: |-
              - op: add
                path: /metadata/labels/istio.io~1global
                value: "true"
