apiVersion: v1
kind: Secret
metadata:
    name: grafana-credential
stringData:
    admin-user: ENC[AES256_GCM,data:AVhKPLcW,iv:qrbNW4h73D36UofCkUjsK7dwEQhMlEjgK94HYo+/7RU=,tag:TV6lh537NyiABSz9v7r/9g==,type:str]
    admin-password: ENC[AES256_GCM,data:+xsN2t50XgVgPg==,iv:Cu2xVgd95uZEqx5EYEbfS5GOwPBY+TvwlD7nerfK4K4=,tag:CW5MUXluarpBPxuifCwUhQ==,type:str]
sops:
    age:
        - recipient: age1k5f087xu2603udrt02z7mxzfrw7tnd6xer3h6dfqc3eruava7qmqauygh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVWRZemRZVFVkSytacGQ4
            clMxemxSN2ZiU2Y3Y0loUFh0QkpaYWhzUlEwCkRhM2prTEplaEtPS3lGQkI4K29j
            UkxITWt2UnlvbzBBRVZGY0E0Vlh6T2cKLS0tIDhoVjRUN3lqNGpiOW9mWHJVaHVW
            NEpLRkhqQytLQXArN2tKTUVBaWQ3dHcK9Erc7skRbgk5DkEZgy6eyKb5YQqmnN7k
            g9UcoB/98rMJKQ1DDn2yQtAKOgc3y4gIkjJuxgKvpKAj6hY4xNtv4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T16:07:48Z"
    mac: ENC[AES256_GCM,data:49QTTG8rHIwitwYvBNCsxcgQtGKzVhFVDD+W1d9HLXc55SzEPcIqS4APVk4CR6IROoW0QjlivzSovreQ2CeFKTSs5FL9dP46hGopPJPhwuVl+qLDexQ+HM7CFKntib0TXjVlW8thVnk5nJajHCx3N3mW578IZFxhA4/9RLHr19c=,iv:m/o9dK7ZsDG0XUZF47sKDCdfILph8/RXk1qoPj4J2Ao=,tag:zzydQ1csG6LpmGqvCOFJEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
