apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-apitoken-secret
stringData:
    api-token: ENC[AES256_GCM,data:foaf08rhRCGaRh1jyR9NQySFy6f+UPaLVqcixQ0bHrNI2TPk9a0Lpg==,iv:2DDp448HtQj86GuNcfyZWNRlKI2oWm/dH5khx3TwoMc=,tag:Qpf6bdKfFjTeRkS3QuWnRA==,type:str]
sops:
    age:
        - recipient: age1k5f087xu2603udrt02z7mxzfrw7tnd6xer3h6dfqc3eruava7qmqauygh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNlVSNjlReDd3bFdJV3pZ
            WXJJL1cxWUlTQlRReGVTQXY2YkN2VGhPQTAwCnJhNVpKdzVYWDBQMlFOajcwUjNw
            Vit2V0dWVVlNbVlybHllT2VSbGxva3cKLS0tIE9mQ1loQXJPOFZpZjdnSmwvcHhO
            SXMyVVYycXhTT0dydkdnVlI5SVFnNU0KqnAEKbkhzsvEEa9g4ZDC9p9HroPwBSAN
            oHXjngLltqrLjV5UcNqoXaGfMAFNHRIwAJYLvaqWOuvxtmcdbvEarw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T16:08:14Z"
    mac: ENC[AES256_GCM,data:vPm254T0Pu14o/cURQYBfmptuEPqtNbcp/y77zymv3yhQobAk7DzX7zsb2GfVQPD2qB9UVFleJENHGmgtYN+80gYEURimr62pTJymFNdpJ0CpgEYA6VQJORXb+l5q6O6toTctrvvnteSqC7JiXuWJldRaIO+TPHrr+LwM4k6fMQ=,iv:4kwk4crAvLkif4fnhOQeakOuntJ+W1O5xhBeM9t5zlA=,tag:fKoJwA3VjAuLyAaBLU9VaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
