---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloakx
spec:
  chart:
    spec:
      chart: .
      reconcileStrategy: Revision
      sourceRef:
        kind: OCIRepository
        name: keycloakx
        namespace: flux-system
  interval: 72h
  valuesFrom: []
