---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloakx
spec:
  chartRef:
    kind: OCIRepository
    name: keycloakx
    namespace: flux-system
  interval: 72h
  valuesFrom: []
