apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure/namespaces.yaml
  - ../../../infrastructure/istio
  - ../../../infrastructure/cert-manager
  - ../../../infrastructure/monitoring-collector
  - ../../../infrastructure/monitoring-stub-services
  - edge-vps-cacerts.yaml
patches:
  - path: patches/istio.yaml
  - path: patches/observability.yaml
