apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure/namespaces.yaml
  - ../../../infrastructure/istio
  - ../../../infrastructure/cert-manager
patches:
  - target:
      kind: HelmRelease
      name: istio-istiod
    patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: istio-istiod
      spec:
        values:
          global:
            meshID: duynch-mesh
            multiCluster:
              clusterName: edge-vps
            network: network-edge
