{{- range $name, $infra := .Values.customGateway.infrastructures }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}

data:
  deployment: |
{{ toYaml $infra.deployment | indent 4 }}

---
{{- end }}
