---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: codecentric
  namespace: flux-system
spec:
  interval: 168h
  url: oci://ghcr.io/codecentric/helm-charts
  secretRef:
    name: oci-registry-creds

