---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: keycloakx
  namespace: flux-system
spec:
  interval: 168h
  url: oci://ghcr.io/codecentric/helm-charts/keycloakx
  ref:
    tag: "7.1.9"
  secretRef:
    name: oci-registry-creds
