apiVersion: v1
kind: ConfigMap
metadata:
  name: values-base
data:
  values.yaml: |-
    crds:
      enabled: true

    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
