---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
spec:
  releaseName: istio-base
  targetNamespace: istio-system
  chart:
    spec:
      chart: base
      version: "1.28.6"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 72h
  valuesFrom:
    - kind: ConfigMap
      name: istio-values
      valuesKey: base-values.yaml
