---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-values
data:
  cni-values.yaml: |-
    ambient:
      enabled: true
    cniBinDir: /var/lib/rancher/k3s/data/cni
    cniConfDir: /var/lib/rancher/k3s/agent/etc/cni/net.d

  ztunnel-values.yaml: |-
    profile: ambient
    resourceName: ztunnel
