---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-values
data:
  base-values.yaml: |-
    global:
      variant: distroless
  cni-values.yaml: |-
    global:
      variant: distroless
    ambient:
      enabled: true
  istiod-values.yaml: |-
    enabled: true
    global:
      variant: distroless
    meshConfig:
      accessLogFile: /dev/stdout
      defaultConfig:
        gatewayTopology:
          numTrustedProxies: 2
    profile: ambient
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
  ztunnel-values.yaml: |-
    variant: distroless
    profile: ambient
    resourceName: ztunnel
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
