apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config-template
data:
  garage.toml.tpl: |
    metadata_dir = "/data/meta"
    data_dir = "/data/blocks"
    db_engine = "lmdb"
    replication_factor = 2
    metadata_fsync = false
    block_size = 1048576

    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "${HOSTNAME}.garage-internal.garage.svc.cluster.local:3901"
    rpc_secret_file = "/secret/rpc_secret"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"

    [admin]
    api_bind_addr = "[::]:3903"
    admin_token_file = "/secret/admin_token"
