apiVersion: v1
kind: Secret
metadata:
  name: garage-secret
stringData:
  rpc-secret: ENC[AES256_GCM,data:y9mO3MWydp3pyQyNimYo8jVygCyv5OutmDveWp8Y4WK7rTrgGeL5WQQUpldq+gqBMLOkB7QOlgppw/5VANSa,iv:LciZC28VSl+3A/ePWsbyNMBNE+RvdzKZlxcN9Y9hNVg=,tag:s3TlxydnqMlBCFrzBHecxg==,type:str]
  admin-token: ENC[AES256_GCM,data:P2MeKUcY/eqhFp5P2M8SztRICWOXeAZIpHTluAnKPgOBJ+hPS+hMhlXrNzc6uOOhs6RTU9E4I2A3hc1ewiGm8A==,iv:dLVSxslxYXsuOpFeXqYNolWLudnBjtFzozV4hxq5His=,tag:s5kKqBjNbP0zye6kgxBNTg==,type:str]
sops:
  age:
    - recipient: age1k5f087xu2603udrt02z7mxzfrw7tnd6xer3h6dfqc3eruava7qmqauygh7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXV0l3UG4yemVKVUZmMHJO
        Z3JsKzVUODhvN2pDYWhWV1VLQTZLMFgyQnpNCmtFVzJyOEhLZ2lIR1g5OVVEYnVa
        bjRySHh1RmhNUVd5b3liNE9nUDRId3cKLS0tIHZuRytIUmE0a09BMEV6MWlIeWdS
        ejZVMHJIaFFxTWhwRVJ1OFlSekpZbjQKZOcdjhCQZR+7w1pHqG3wnnKA8GBYQyRL
        2RuPh7zyG5XtWYWw3sO5dHWDgryj89ZmVFnorMhp9FcGDX9kplMgvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-18T16:27:21Z"
  mac: ENC[AES256_GCM,data:5nhKFa6JdtpZnGHUzMi8mnMgH9bz1IbSVHjnKfGwCbYxFXFSfH3NkeKuFhhMdbUIDIiyRz4StOWLvSeAk8yA+eY4qX40Kz9pl+ucStP51+rlOBDbyPUQxvuWm6PRkyqqF9u+vzh1/dUe7ZQcDDRUKWUgo8HnMP/6cHh31GwZ3AU=,iv:nVqtD2UBjGKokNnCj2jgrBcGz157LIY5N8FPTvusrj4=,tag:BJqZFrtiBsTzlPAS4LrVnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
