apiVersion: v1
data:
    admin-token: ENC[AES256_GCM,data:fe5RayiDTxPSrjwl0Hts2+GU+MRHbfOezLGIxzvNMhWVDbmtz9E8wfTIF2HKvJtPjbYAyazBNyGfTFi54YXYNgBDsr3937JV61WAbJMcbDxSTR95VWiXUA==,iv:7tBUAHBQHc0DIhoYapPKyew0l+d5yKpC7bOZjMItm3E=,tag:45Pj7BcHFAcvBGu+UtZWHg==,type:str]
    rpc-secret: ENC[AES256_GCM,data:j9flyGKkuNKyPgVC+wiZChT32OKQ26i7h6OxCja72n+417P1feIaEI1rpF5/vkok6w0tuUupB2U9N0TA+oS88JLfP33ZhN783mjJjxKNlfP7RhmMFsqx0Q==,iv:ZybZ/VkMbKVJbDT7Vu3DIN2V9r4KARG8GcX4Fiwk+8M=,tag:0dK9HnxURYkCL32Et0UhoA==,type:str]
kind: Secret
metadata:
    name: garage-secret
    namespace: garage
sops:
    age:
        - recipient: age1k5f087xu2603udrt02z7mxzfrw7tnd6xer3h6dfqc3eruava7qmqauygh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTzBTZXBWaHA4cVRyczN5
            S05waUJZQjNaZjltNzdkQk42dFdoRFlLYVZjCis5WHJtTUZlZThzdTYzRnlMV2Fw
            VVhWL3p1RFhpUXVZSzArU1JXZW1sZlUKLS0tIHhyWmoxelRzS1ZSbUN4MTBEdG55
            dVpQclUrVDByTU5FVEZXeTQxaGJ0TEUKY6UQNRUJGrQpWWW7g5tTq2hT9yw0QFZD
            J9Wz2Np7nbzRGDJY69vHpldk0GeNZ/eQERhILIoB/eP8O/hZJYejgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T17:16:35Z"
    mac: ENC[AES256_GCM,data:v4fc2u/z+miwUnEKOW3Ro4r4YZbQtUaeNiKUHZ2je7ykwVoC5CUulYpBXMU7yqNaP3jq1E0M+RlCThE0NJPCmRvuVwLhMJrpYMoEV3njMTRS4ncR6kXqhrSKOYIuA/axMSvp5fWeEe5RWw2jKraRXUiXTzJHDQT22XJpcf5wCb4=,iv:HMWi9JB9iWdnl/4XOXWLU6ddgYj507Y2djW4kSNElec=,tag:ZQwqkMDWQOcV7FbfFG7SXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
