apiVersion: v1
kind: Secret
metadata:
    name: fluent-bit-secret
stringData:
    ES_USER: ENC[AES256_GCM,data:LuUpsbFK,iv:2a7xyhXD2ooH2EShqOn+g8BOc7U1Cm19AhKkrZXx950=,tag:UdR+N2xRxJu6CCVRtntGvQ==,type:str]
    ES_PASSWD: ENC[AES256_GCM,data:fltoUGZkN2H6tUDUjfgrHTh0KcU=,iv:wIwHXRhaFcCWPoUiR+REJAgOlNkJPIpJN+lM8UrnxPU=,tag:3p4hKf6vWwEoLfUCucdFZw==,type:str]
sops:
    age:
        - recipient: age1k5f087xu2603udrt02z7mxzfrw7tnd6xer3h6dfqc3eruava7qmqauygh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZVB4bFF1emh4bVRmb0tX
            YmpmdVpiRkVmNi9PVlhuYkNjTjFPMmplU2xNCk5UYWFFbXhVK0Y2NFhxbWVTUUZz
            VzZNb0pVaDlCS2d5U0UzSjBkeHMrdzQKLS0tIERoT053dnp0WHdUNEg5WENaZWwx
            VStKV215dEE2VlFtZTU2anJMaEhpR1EK4nBe1u5bX2JHXTsKD1u320yy/6D8K7Cy
            5lKQ5YW3IiABPetoejly9ZpbskZ6Bh7JSOE5Rm0j/5pJKy4HYCFfPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T16:07:14Z"
    mac: ENC[AES256_GCM,data:udJfYbTwdKRlToazlNBj0Epohn2DBue3yVACUIi+g7KY6tM9fbRp3CnqIpwI27OKMjPs9oXNnKtxjR3NR0p0Pah+U7UD9EIlweuXQX2QY27qTiuvqHTa4kZtyyN9tX5yhbATyhdZ0+NXO7MUQPbm0Sb1YFLikVpqimWNuUo1ZOU=,iv:q61y1xFYrYL8PODN++dkppUNO/PzaUP/acZJqWnuWF8=,tag:0OePnndoHk30SsJe3YZVqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
