apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: nguyenchauhieuduy@outlook.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - selector:
          dnsZones:
            - "duynch.com"
            - "*.duynch.com"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-apitoken-secret
              key: api-token
      - selector:
          dnsZones:
            - "khoanguyen.io.vn"
        http01:
          gatewayHTTPRoute:
            parentRefs:
              - group: gateway.networking.k8s.io
                kind: Gateway
                name: external-gateway
                namespace: ingress-external
