apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
spec:
  values:
    global:
      meshID: duynch-mesh
      multiCluster:
        clusterName: homelab
      network: network-homelab
