apiVersion: v1
kind: Secret
metadata:
    name: keycloak-app-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:E5W0si5WYu1RC5fA,iv:wERIm69RlWEgbyl+7rQ18FeHqv3vHDz2rGq1HOZLudA=,tag:h5wKvNKWxANxvD+qoqAK6w==,type:str]
    password: ENC[AES256_GCM,data:VNQHg7Dt+5EUhvsBzXB8nP0ltb4eGhbqIcxVON2K9xM=,iv:5Y5P8Xf7DWGHnq8GbP67xNpuQiN/TP26ZOG79gcu0wo=,tag:4HyqkrTQAf0k3bZRSyJI0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVVJRU1lFaTFmYXdNUkU0
            ZTQ4a2lQMkZMdXdKQXFkRWU2L3p6a2FZK2lNCjkwTTZaU25RREYzZGIvK2ZxZ05N
            ck8wMDB5M05BVDIrNjRzR1RpMjRCN3cKLS0tIHhmeWJyYkQzQjYwM0tZUjJuT0pZ
            cW5ZSDJQNGlTUmEyVVdEVlMvRVB4aWMKC3Io3vYerCRa2BjsXo8gfYQU04dMs95y
            laMu6sVk7ioWrKKFdFQ5HZkKlP8frsZE7ki7a+4FugFg0L8lROppOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5f087xu2603udrt02z7mxzfrw7tnd6xer3h6dfqc3eruava7qmqauygh7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T14:17:52Z"
    mac: ENC[AES256_GCM,data:nZgY4yflDV0F56q9D8aMtuk/MrIHyhPRSNQXmVg1GADUwk6R9mmpQlav23nbEUWhIe0aSZ+3poTZt+ED5nCopVIRFotbg0lPEd0JT9tawIlETUD8KTYFEIuLRbZ0AX74RvCllchpogTts76OtNttwZwlR/piRwZRwuMiZELEGbk=,iv:V2DQ0jyjpjGeHD6OVd+vaPFGRbu55TcsXmBqmpxODLY=,tag:HT9V6eTJ95/qUiq/ygepkg==,type:str]
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-readonly-secret
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:G60SiRdA0dm71SEZWfAGm7M=,iv:CMSKk4Bo4A8Xy91ILeBV3k44vMDJyWPlDrIcIUt+WX4=,tag:1JoGi2+1RsLM0HhU/W51KA==,type:str]
    password: ENC[AES256_GCM,data:mKhQFOjGKdOUlJ7Wh9WbqrwPLdZrfFgyiM0DNduzfg==,iv:OOxsbooGVNwWqHTUYkkOHjgdM7XPSil18ovhHQ82aFY=,tag:FwAtrwwQRy49skG7oGZK0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVVJRU1lFaTFmYXdNUkU0
            ZTQ4a2lQMkZMdXdKQXFkRWU2L3p6a2FZK2lNCjkwTTZaU25RREYzZGIvK2ZxZ05N
            ck8wMDB5M05BVDIrNjRzR1RpMjRCN3cKLS0tIHhmeWJyYkQzQjYwM0tZUjJuT0pZ
            cW5ZSDJQNGlTUmEyVVdEVlMvRVB4aWMKC3Io3vYerCRa2BjsXo8gfYQU04dMs95y
            laMu6sVk7ioWrKKFdFQ5HZkKlP8frsZE7ki7a+4FugFg0L8lROppOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5f087xu2603udrt02z7mxzfrw7tnd6xer3h6dfqc3eruava7qmqauygh7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T14:17:52Z"
    mac: ENC[AES256_GCM,data:nZgY4yflDV0F56q9D8aMtuk/MrIHyhPRSNQXmVg1GADUwk6R9mmpQlav23nbEUWhIe0aSZ+3poTZt+ED5nCopVIRFotbg0lPEd0JT9tawIlETUD8KTYFEIuLRbZ0AX74RvCllchpogTts76OtNttwZwlR/piRwZRwuMiZELEGbk=,iv:V2DQ0jyjpjGeHD6OVd+vaPFGRbu55TcsXmBqmpxODLY=,tag:HT9V6eTJ95/qUiq/ygepkg==,type:str]
    version: 3.13.1
