---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: codecentric
  namespace: flux-system
spec:
  interval: 7d
  type: oci
  url: oci://ghcr.io/codecentric/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloakx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keycloax
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: OCIRepository
        name: codecentric
      version: 7.1.5
  interval: 3d
  valuesFrom:
    - kind: ConfigMap
      name: cluster-authen-values
      valuesKey: values.yaml
