apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-authen-values
data:
  values.yaml: |-
    replicas: 1
    command:
    - /opt/keycloak/bin/kc.sh
    - start
    - --http-port=8080
    - --hostname-strict=false
    - --proxy-headers=xforwarded
    proxy:
      enabled: true
      http:
        enabled: true
      mode: forwarded

