---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path
  volumeMode: Filesystem
