apiVersion: v1
kind: Secret
metadata:
    name: keycloakx-secret
stringData:
    KEYCLOAK_ADMIN: ENC[AES256_GCM,data:TxuDZYMt09bg9bUA,iv:+md7EZpdfy+CDePNaWnKGyn7gXNejI1ZATJ2FKOclN8=,tag:3D6ZiRrJaW8UFxAAL+UFZw==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:DorAs3/iZOfYRA6TNHhV0LiTXYE=,iv:qA+Zgb1Ky1H/f6iGQ8XFpMetp2N7CvngqdryJeNpXG8=,tag:gyaO0AaFYL5p712wWDS8aQ==,type:str]
    KC_DB: ENC[AES256_GCM,data:cJtOKQZBIQ8=,iv:8vYocfrr4REOUtrQHNFReEBrvVhdqt+nmN0rmTcYZeM=,tag:eLSgRrrJ9w9zLNX+fb5+Vg==,type:str]
    KC_DB_USERNAME: ENC[AES256_GCM,data:9LWhZIDjCw==,iv:PIXkBsKjfcJqX6UUaKCUh0JPW73XEGMcc3veEfFh7sY=,tag:g5WPIKMGJFpsc/OXc37fuw==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:qGxkDYyHOS/ZrPysxiOwQy5tc9w=,iv:P0X7uOh9YRRXvYtD0Gu4nJx/IZFEDFjfXCfDJIxr3I0=,tag:1U49FlqqfHQn6CwFdExsRQ==,type:str]
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:XAqWKf4=,iv:9ZgFlQj7bWZ0On3u19oeCruJB8XuQQs0lM/Iccb83EY=,tag:LNuS/yek6BxFQ6GHPpR5Vw==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:vkxYZ38=,iv:ZVb2xqbzZfesqMesVJCJ4YuUwr+8MfmEhiEKGzYxODY=,tag:3BcgWan/hMct0vsRAw7m6A==,type:str]
sops:
    age:
        - recipient: age1k5f087xu2603udrt02z7mxzfrw7tnd6xer3h6dfqc3eruava7qmqauygh7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaDlkT0t5L2tOMUhWN0p2
            Y3lsN2w4L2YxZTJISUNuKy9vNlFRUk9MYmtrCndmTSt6U2MrdE5kb09rTG9NMWhG
            TDhtUDIxVFhQV2JJTlZWcEYvOGJtRzgKLS0tIFlTTWtpd2RYNHpPVUlZWm4vc0l1
            VjM2T0tJd0FmQVdaRFBBNy8vVENIN3MKLxfMH/weif4k2yGlo+9H5dps0n4Wz3ic
            +6GvLhl9VSTogAtcvMze4OiQPJjMdKMghnJdZw3pbo9IS41fgfPPyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T16:03:46Z"
    mac: ENC[AES256_GCM,data:Fd7Hban/9O+G5UQRtsRfFICJMOoQADhStUVrawGwVRKS7qHTOOgnvyrW1vOAvESwHRZxlgO+/0IRB6VsvhHXbXphQBT8HolyDlL1BByrvO43fAUrqQxstelAP01K4WBqlZG3BuQxXFhNJ+m/aFzanxTKGxC45xHQNV/HBk+IcEw=,iv:ReO7NV2c6VJa09qhIuh6XzQtWHq/n0M5/ryITlRWnkc=,tag:+obB/hbWyT8uLfs8dB3EwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
