apiVersion: v1
kind: Secret
metadata:
    name: keycloakx-secret
stringData:
    KEYCLOAK_ADMIN: ENC[AES256_GCM,data:pXgMXoE=,iv:0qXR1AKyJbWt/fRDdtJRumnHfVMeIfrvy/CIE3VQc8Q=,tag:/0dw7W+KC1dlRBCsJLzjhQ==,type:str]
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:0UDFSY2fHS0Jx5j+GVOo4HsOQC73wTUEsq8GacPCXWc=,iv:EZQptoS930eJdefg1GM55h2RFicWsHd/cCknvr3F9i8=,tag:J7l6+HOHi3YR6cZV+NaupQ==,type:str]
    KC_DB: ENC[AES256_GCM,data:rknDiLTKohY=,iv:MdiuH0raTv6tdHmec4vVgqlK68hFWM9J9UI+v0nAs38=,tag:vovciDwbmxJg39fbHxs9Fw==,type:str]
    KC_DB_URL: ENC[AES256_GCM,data:QDiQzQ7fZRIY65psdBWo+sNswOei89o7qZR3CHVJuXKqXg2kUmGGbRvBywczh3W9G3+WKh95VnQ9VX0u0VV5/EVkiX8PmFkLjglLvmxFQ2o=,iv:kkclN75+ImoqMxQLaklqcJzOMWag2vLmO2Qft2tNocI=,tag:AUqqpFFn6a/jU7k3vtiVQw==,type:str]
    KC_DB_USERNAME: ENC[AES256_GCM,data:q00f0SRjn8eLRP7D,iv:BLKvbz6iiHsy32E5VzUwncpt6cIyHYPyseXRvvk6d0k=,tag:rqo7ukU+e+9LMoOG/ZcppA==,type:str]
    KC_DB_PASSWORD: ENC[AES256_GCM,data:GnE/HFsr5RYeABN6JQV6oiXi5xmRylMZqQZPWvLw+K8=,iv:wYTBG1wvXlprXcIwYyDdLZFaoLn1BYtJI3/ngDDVvr4=,tag:3EWms/oPnND5q46ICNcsTg==,type:str]
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:XAqWKf4=,iv:9ZgFlQj7bWZ0On3u19oeCruJB8XuQQs0lM/Iccb83EY=,tag:LNuS/yek6BxFQ6GHPpR5Vw==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:vkxYZ38=,iv:ZVb2xqbzZfesqMesVJCJ4YuUwr+8MfmEhiEKGzYxODY=,tag:3BcgWan/hMct0vsRAw7m6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaDlkT0t5L2tOMUhWN0p2
            Y3lsN2w4L2YxZTJISUNuKy9vNlFRUk9MYmtrCndmTSt6U2MrdE5kb09rTG9NMWhG
            TDhtUDIxVFhQV2JJTlZWcEYvOGJtRzgKLS0tIFlTTWtpd2RYNHpPVUlZWm4vc0l1
            VjM2T0tJd0FmQVdaRFBBNy8vVENIN3MKLxfMH/weif4k2yGlo+9H5dps0n4Wz3ic
            +6GvLhl9VSTogAtcvMze4OiQPJjMdKMghnJdZw3pbo9IS41fgfPPyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5f087xu2603udrt02z7mxzfrw7tnd6xer3h6dfqc3eruava7qmqauygh7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T15:31:53Z"
    mac: ENC[AES256_GCM,data:7xFOllwSfWftJifBbRn3VI0c58JE8ORKOFSh9qFzTZAyvpl4f2vgzR+/LAnLdZiOxtfGkJGzY3ublrePDt6QKrubqdv/jzoaLcjx4qCGW8euv/Gkj8lbn2qXaA+AKQJma6OtaG3FMSTnaHWKOBCPtGrOiSfFYnFCIBVYD5fErnY=,iv:XIP31E/Y1Zx7SEXHvfvZr+iEIQV7GUgi9CoptygDz04=,tag:Exriws/Ti8vzTyMrPKD0WQ==,type:str]
    version: 3.13.1
