---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authen-values
data:
  values.yaml: |-
    extraEnvFrom: |
      - secretRef:
          name: keycloakx-secret-staging

    httpRoute:
      enabled: true
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: http-gateway
          namespace: ingress-internal
          sectionName: https
      hostnames:
        - iam.duynch.lab
