---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes-service.exposed-to: both
  name: networking-stack
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes-service.exposed-to: internal
  name: storage
spec: {}
