{
 "title": "Servers Overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 -\r\n    (\r\n    avg by (instance) (node_memory_MemAvailable_bytes{job=\"node-exporter\"}) / \r\n    avg by (instance) (node_memory_MemTotal_bytes{job=\"node-exporter\"}) * 100\r\n    )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  1 -\r\n    avg by (instance) (\r\n    rate(\r\n      node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\"}[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File System Usage (%)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 * (1- (max by (mountpoint, instance) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=~\"/|/data|/var\"})) / max by (mountpoint, instance) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=~\"/|/data|/var\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IO (read/write total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  rate(node_disk_read_bytes_total{job=\"node-exporter\"}[5m])\r\n  +\r\n  rate(node_disk_written_bytes_total{job=\"node-exporter\"}[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}