apiVersion: v2
name: efk
version: 0.0.0

dependencies:
  - name: fluent-bit
    version: 0.56.0
    repository: "oci://ghcr.io/fluent/helm-charts"
  - name: eck-stack
    version: 0.17.0
    repository: "https://helm.elastic.co"
