{{- range .Values.clusterIssuers }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  acme:
    privateKeySecretRef:
      name: {{ .privateKeyName }}
    server: {{ .server }}
    solvers:
{{ toYaml .solvers | indent 6 }}
{{- end }}
